import { calculateMockStrokeRisk } from "./mockModel.js";

const RAW_FEATURE_KEYS = [
  "age",
  "hypertension",
  "heart_disease",
  "ever_married",
  "work_type",
  "avg_glucose_level",
  "bmi",
  "smoking_status"
];

function normalizeAiResult(aiJson) {
  const nestedPrediction = aiJson.prediction ?? aiJson.data ?? aiJson.result ?? aiJson;

  const rawProbability =
    nestedPrediction.probability ??
    nestedPrediction.risk_score ??
    nestedPrediction.riskScore ??
    nestedPrediction.percentage ??
    nestedPrediction.stroke_probability ??
    nestedPrediction.strokeProbability ??
    nestedPrediction.probabilityPercent ??
    0;

  let probabilityPercent = Number(rawProbability);

  if (Number.isNaN(probabilityPercent)) {
    probabilityPercent = 0;
  }

  if (probabilityPercent <= 1) {
    probabilityPercent *= 100;
  }

  probabilityPercent = Math.min(Math.max(probabilityPercent, 0), 100);
  probabilityPercent = Math.round(probabilityPercent * 100) / 100;

  let riskLevel =
    nestedPrediction.riskLevel ??
    nestedPrediction.risk_level ??
    nestedPrediction.label ??
    nestedPrediction.classification;

  if (typeof riskLevel === "string") {
    const normalized = riskLevel.toLowerCase();
    if (normalized.includes("high")) riskLevel = "High";
    else if (normalized.includes("medium") || normalized.includes("moderate")) riskLevel = "Medium";
    else if (normalized.includes("low")) riskLevel = "Low";
  }

  if (!riskLevel) {
    if (probabilityPercent >= 70) riskLevel = "High";
    else if (probabilityPercent >= 35) riskLevel = "Medium";
    else riskLevel = "Low";
  }

  return {
    probabilityPercent,
    riskLevel,
    factors: nestedPrediction.factors ?? [],
    recommendations: nestedPrediction.recommendations ?? [
      "This result is generated by the AI model endpoint.",
      "This screening result is not a medical diagnosis.",
      "Please consult a healthcare professional for medical decisions."
    ],
    disclaimer: "This is an AI-assisted screening result, not a medical diagnosis.",
    rawAiResponse: aiJson
  };
}

function buildAiPayload(input) {
  const rawFeatures = {};

  for (const key of RAW_FEATURE_KEYS) {
    rawFeatures[key] = input[key];
  }

  return {
    mode: "raw",
    raw_features: rawFeatures
  };
}

export async function getPrediction(input) {
  const aiApiUrl = process.env.AI_API_URL;

  if (!aiApiUrl) {
    return {
      modelSource: "mock-backend-placeholder",
      modelVersion: "mock-v1",
      prediction: calculateMockStrokeRisk(input)
    };
  }

  try {
    const response = await fetch(aiApiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(buildAiPayload(input))
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`AI API returned status ${response.status}: ${errorText}`);
    }

    const aiJson = await response.json();

    return {
      modelSource: "ai-api",
      modelVersion: process.env.AI_MODEL_VERSION || "ai-api-v1",
      prediction: normalizeAiResult(aiJson)
    };
  } catch (error) {
    return {
      modelSource: "mock-fallback-ai-unavailable",
      modelVersion: "mock-v1",
      prediction: {
        ...calculateMockStrokeRisk(input),
        warning: `AI API was unavailable, so backend used mock prediction. Reason: ${error.message}`
      }
    };
  }
}
